[fragments]


[operations]

MUTATION_CREATE_UPLOAD = """
mutation createUpload(
  $blobId: ID!, 
  $store: BlobStoreInput = {
    label: "default", 
    type: NVA_CLOUD
  }, 
  $parts: Int = 1
) {
  createUpload(
    store: $store, 
    blobId: $blobId, 
    parts: $parts
  ) {
    blobId
    uploadId
    parts {
      partNumber
      url
    }
  }
}
"""

MUTATION_COMPLETE_UPLOAD = """
mutation CompleteUpload (
  $blobId: ID!, 
  $completedUpload: CompletedUploadInput!,
) {
  completeUpload(
    store: {
      label: "default", 
      type: NVA_CLOUD
    },
    blobId: $blobId
    completedUpload: $completedUpload
  )
}
"""

MUTATION_COMPLETE_UPLOAD_SINGLE = """
mutation completeUpload(
  $blobId: ID!, $uploadId: ID!, 
  $eTag: String, 
  $store: BlobStoreInput = {
    label: "default", 
    type: NVA_CLOUD
  }
) {
  completeUpload (
    store: $store,
    blobId: $blobId,
    completedUpload: {
      uploadId: $uploadId,
      parts: [
        {
          partNumber: 1,
          eTag: $eTag
        }
      ]
    }
  )
}
"""

MUTATION_CREATE_DOWNLOAD = """
mutation createDownload(
  $blobId: ID!,
  $label: String = "default",
  $type: BlobStoreType = NVA_CLOUD
) {
  createDownload(blobId: $blobId, store: {label: $label, type: $type})
}
"""

MUTATION_DELETE_BLOB = """
mutation deleteBlob(
  $blobId: ID!,
  $label: String = "default",
  $type: BlobStoreType = NVA_CLOUD
) {
  deleteBlob(blobId: $blobId, store: {label: $label, type: $type})
}
"""
