# =================================================
# Fragments
# =================================================

[fragments]

FRAGMENT_BLOBENTRY = """
fragment FRAGMENT_BLOBENTRY on BlobEntry {
  id
  blobId
  originId
  label
  blobstore
  hash
  origin
  size
  description
  mimeType
  metadata
  timestamp
  createdTimestamp
  lastUpdatedTimestamp
  _version
}
"""

# =================================================
# Operations
# =================================================

[operations]

QUERY_GET_BLOBENTRY = """
query getBlobEntry(
  $id: ID!
) {
  blobEntries(where: { id: $id }) {
    ...FRAGMENT_BLOBENTRY
  }
}
"""

QUERY_GET_BLOBENTRIES = """
query geBlobEntries(
  $id: ID!
) {
  variables(where: { id: $id }) {
    blobEntries {
      ...FRAGMENT_BLOBENTRY
    }
  }
}
"""

MUTATION_ADD_BLOBENTRIES = """
mutation addBlobEntries($blobEntries: [BlobEntryCreateInput!]!) {
  addBlobEntries(
    input: $blobEntries
  ) {
    blobEntries {
      ...FRAGMENT_BLOBENTRY
    }
  }
}
"""

QUERY_LIST_BLOBENTRIES = """
query listBlobEntries($id: ID!) {
  variables (
    where: {id: $id}
  ) {
    blobEntries {
      label
    }
  }
}
"""

QUERY_LIST_FACTORGRAPH_BLOBENTRIES = """
query listGraphBlobEntries($id: ID!) {
  factorgraphs(where: { id: $id }) {
    blobEntries {
      label
    }
  }
}
"""

QUERY_LIST_AGENT_BLOBENTRIES = """
query listAgentBlobEntries($id: ID!) {
  agents(where: { id: $id }) { 
    blobEntries {
      label
    } 
  }
}
"""

QUERY_LIST_MODEL_BLOBENTRIES = """
query listModelBlobEntries($id: ID!) {
  models(where: { id: $id }) { 
    blobEntries {
      label
    } 
  }
}
"""

GQL_GET_FG_BLOBENTRIES = """
query getGraphBlobEntries($id: ID!) {
  factorgraphs(where: { id: $id }) {
    blobEntries {
      ...FRAGMENT_BLOBENTRY
    }
  }
}
"""

QUERY_GET_AGENT_BLOBENTRIES = """
query getAgentBlobEntries($id: ID!) {
  agents(where: { id: $id }) { 
    blobEntries {
      ...FRAGMENT_BLOBENTRY
    } 
  }
}
"""

QUERY_GET_MODEL_BLOBENTRIES = """
query getModelBlobEntries($id: ID!) {
  models(where: { id: $id }) { 
    blobEntries {
      ...FRAGMENT_BLOBENTRY
    } 
  }
}
"""

QUERY_DELETE_BLOBENTRY = """
mutation deleteBlobEntry($id: ID!) {
  deleteBlobEntries(where: { id: $id }) {
    nodesDeleted
  }
}
"""
