# =================================================
# Factor Fragments
# =================================================

[fragments]

FRAGMENT_FACTOR_SKELETON = """
fragment FRAGMENT_FACTOR_SKELETON on Factor {
  id
  label
  tags
  _variableOrderSymbols
}
"""

FRAGMENT_FACTOR_SUMMARY = """
fragment FRAGMENT_FACTOR_SUMMARY on Factor {
  timestamp
  nstime
}
"""

FRAGMENT_FACTOR = """
fragment FRAGMENT_FACTOR on Factor {
  fnctype
  solvable
  data
  metadata
  _version
}
"""

# =================================================
# Factor Operations
# =================================================

[operations]

QUERY_GET_FACTOR = """
query getFactor(
  $facId: ID!,
  $fields_summary: Boolean! = true,
  $fields_full: Boolean! = true
) {
  factors(where: { id: $facId }) {
    ...FRAGMENT_FACTOR_SKELETON
    ...FRAGMENT_FACTOR_SUMMARY @include(if: $fields_summary)
    ...FRAGMENT_FACTOR @include(if: $fields_full)
  }
}
"""

QUERY_GET_FACTORS = """
query getFactors(
  $fgId: ID!,
  $fields_summary: Boolean! = true,
  $fields_full: Boolean! = true
) {
  factorgraphs(where: { id: $fgId }) {
    factors {
      ...FRAGMENT_FACTOR_SKELETON
      ...FRAGMENT_FACTOR_SUMMARY @include(if: $fields_summary)
      ...FRAGMENT_FACTOR @include(if: $fields_full)
    }
  }
}
"""

QUERY_GET_FACTORS_FILTERED = """
query getFactors_filtered(
    $sessionId: ID!,
    $factor_label_regexp: String = ".*",
    $factor_tags: [String] = ["FACTOR"],
    $solvable: Int! = 0,
    $fields_summary: Boolean! = false, 
    $fields_full: Boolean! = false
){
  factors( where: {
        session: {id: $sessionId},
        label_MATCHES: $factor_label_regexp, 
        tags: $factor_tags, 
        solvable_GTE: $solvable},
        options: { sort: [{ label: ASC } ]}) {
      ...FRAGMENT_FACTOR_SKELETON
      ...FRAGMENT_FACTOR_SUMMARY @include(if: $fields_summary)
      ...FRAGMENT_FACTOR @include(if: $fields_full)
  }
}
"""

MUTATION_ADD_FACTORS = """
mutation addFactors($factorsToCreate: [FactorCreateInput!]!) {
  addFactors(
    input: $factorsToCreate
  ) {
    factors {
      ...FRAGMENT_FACTOR_SKELETON
      ...FRAGMENT_FACTOR_SUMMARY
      ...FRAGMENT_FACTOR
    }
  }
}
"""

QUERY_LISTFACTORS = """
query listFactors($fgId: ID!, $where: ListWhere = {}) {
  listFactors(fgId: $fgId, where: $where)
}
"""

MUTATION_DELETE_FACTOR = """
mutation deleteFactor($factorId: ID!) {
  deleteFactors(
    where: { id: $factorId }
    delete: {
      blobEntries: {
        where: {
          node: { parentConnection: {Factor: { node: { id: $factorId } } } }
        }
      }
    }
  ) {
    nodesDeleted
    relationshipsDeleted
  }
}
"""