# =================================================
# Variable Fragments
# =================================================

[fragments]

FRAGMENT_PPE_FIELDS = """
fragment FRAGMENT_PPE_FIELDS on Ppe {
  solveKey
  suggested
  max
  mean
  lastUpdatedTimestamp
}"""

FRAGMENT_SOLVERDATA_FIELDS = """
fragment FRAGMENT_SOLVERDATA_FIELDS on SolverData {
  solveKey
  BayesNetOutVertIDs
  BayesNetVertID
  dimIDs
  dimbw
  dims
  dimval
  dontmargin
  eliminated
  infoPerCoord
  initialized
  ismargin
  separator
  solveInProgress
  solvedCount
  variableType
  vecbw
  vecval
  _version
}"""

# =================================================
# Factor Fragments
# =================================================

FRAGMENT_FACTOR_SKELETON_FIELDS = """
fragment FRAGMENT_FACTOR_SKELETON_FIELDS on Factor {
  label
  tags
  _variableOrderSymbols
}"""

FRAGMENT_FACTOR_SUMMARY_FIELDS = """
fragment FRAGMENT_FACTOR_SUMMARY_FIELDS on Factor {
  timestamp
  _version
}"""

# =================================================
# Variable Operations
# =================================================

[operations]

QUERY_GET_VARIABLE = """
query QUERY_GET_VARIABLE(
  $userId: ID!,
  $robotId: ID!,
  $sessionId: ID!,
  $label: ID!) {
    users(where:{id: $userId}) {
      robots(where:{id: $robotId}) {
        sessions(where:{id: $sessionId}) {
          variables(where:{label: $label}) {
            ...variable_skeleton_fields
            ...variable_summary_fields
            ...variable_full_fields
          }
        }
      }
    }
  }"""

QUERY_LIST_VARIABLE = """
query QUERY_LIST_VARIABLE($userLabel: String!, $robotLabel: String!, $sessionLabel: String!) {
  users(where: { label: $userLabel }) {
    robots(where: { label: $robotLabel }) {
      sessions(where: { label: $sessionLabel }) {
        variables {
          label
        }
      }
    }
  }
}"""

# =================================================
# Factor Operations
# =================================================

QUERY_GET_FACTOR = """
query QUERY_GET_FACTOR(
  $userId: ID!,
  $robotId: ID!,
  $sessionId: ID!,
  $label: ID!) {
    users(where:{id: $userId}) {
      robots(where:{id: $robotId}) {
        sessions(where:{id: $sessionId}) {
          factors(where:{label: $label}) {
            ...factor_skeleton_fields
            ...factor_summary_fields
            ...factor_full_fields
          }
        }
      }
    }
  }"""
