# =================================================
# Fragments
# =================================================

[fragments]

FRAGMENT_PPE = """
fragment FRAGMENT_PPE on PPE {
    id
    solveKey
    suggested
    max
    mean
    _type
    _version
    createdTimestamp
    lastUpdatedTimestamp
  }
"""

# =================================================
# Operations
# =================================================

[operations]

QUERY_GET_PPE = """
query getPpe($id: ID!) {
  ppes(where: { id: $id }) {
    ...FRAGMENT_PPE
  }
}
"""

QUERY_GET_PPES = """
query getPpes($id: ID!) {
  variables(where: { id: $id }) {
    ppes {
      ...FRAGMENT_PPE
    }
  }
}
"""

MUTATION_ADD_PPES = """
mutation addPpes($ppes: [PPECreateInput!]!) {
  addPpes(input: $ppes) {
    ppes {
      ...FRAGMENT_PPE
    }
  }
}
"""

QUERY_LIST_PPES = """
query listPpes($id: ID!) {
  variables (where: {id: $id}) {
    ppes {
      solveKey
    }
  }
}
"""

MUTATION_UPDATE_PPE = """
mutation updatePpe($id: ID!, $ppe: PPEUpdateInput!) {
  updatePpes(
    update: $ppe
    where: {id: $id}
  ) {
    ppes {
      ...FRAGMENT_PPE
    }
  }
}
"""

MUTATION_DELETE_PPE = """
mutation deletePpe($id: ID!) {
  deletePpes(where: { id: $id }) {
    nodesDeleted
  }
}
"""
