# =================================================
# Fragments
# =================================================

[fragments]

FRAGMENT_SOLVERDATA = """
fragment FRAGMENT_SOLVERDATA on SolverData {
  id
  vecval
  dimval
  vecbw
  dimbw
  BayesNetOutVertIDs
  dimIDs
  dims
  eliminated
  BayesNetVertID
  separator
  variableType
  initialized
  infoPerCoord
  ismargin
  dontmargin
  solveInProgress
  solvedCount
  solveKey
  covar
  _version  
}
"""

# =================================================
# Operations
# =================================================

[operations]

QUERY_GET_SOLVERDATA = """
query getVariableSolverData(
  $id: ID!
) {
  solverData(where: { id: $id }) {
    ...FRAGMENT_SOLVERDATA
  }
}
"""

QUERY_GET_SOLVERDATA_ALL = """
query getSolverDataAll(
  $id: ID!
) {
  variables(where: { id: $id }) {
    solverData {
      ...FRAGMENT_SOLVERDATA
    }
  }
}
"""

MUTATION_ADD_SOLVERDATA = """
mutation addVariableSolverData($solverData: [SolverDataCreateInput!]!) {
  addSolverData(
    input: $solverData
  ) {
    solverData {
      ...FRAGMENT_SOLVERDATA
    }
  }
}
"""

QUERY_LIST_SOLVERDATA = """
query listVariableSolverData($id: ID!) {
  variables (
    where: {id: $id}
  ) {
    solverData {
      solveKey
    }
  }
}
"""

MUTATION_UPDATE_SOLVERDATA = """
mutation updateVariableSolverData(
  $id: ID!, 
  $solverData: SolverDataUpdateInput!
) {
  updateSolverData(
    update: $solverData
    where: {id: $id}
  ) {
    solverData {
      ...FRAGMENT_SOLVERDATA
    }
  }
}
"""

MUTATION_DELETE_SOLVERDATA = """
mutation deleteVariableSolverData($id: ID!) {
  deleteSolverData(where: { id: $id }) {
    nodesDeleted
  }
}
"""
