# =================================================
# Fragments
# =================================================

[fragments]

FRAGMENT_VARIABLE_SKELETON = """
fragment FRAGMENT_VARIABLE_SKELETON on Variable {
    id
    label
    tags
  }
"""

FRAGMENT_VARIABLE_SUMMARY = """
fragment FRAGMENT_VARIABLE_SUMMARY on Variable {
  timestamp
  nstime
  ppes {
    ...FRAGMENT_PPE
  }
  blobEntries {
    ...FRAGMENT_BLOBENTRY
  }
  variableType
  _version
}
"""

FRAGMENT_VARIABLE = """
fragment FRAGMENT_VARIABLE on Variable {
  metadata
  solvable
  solverData
  {
    ...FRAGMENT_SOLVERDATA
  }
}
"""

# =================================================
# Operations
# =================================================

[operations]

QUERY_GET_VARIABLE = """
query getVariable(
  $varId: ID!
  $fields_summary: Boolean! = true
  $fields_full: Boolean! = true
) {
    variables(where: { id: $varId }) {
      ...FRAGMENT_VARIABLE_SKELETON
      ...FRAGMENT_VARIABLE_SUMMARY @include(if: $fields_summary)
      ...FRAGMENT_VARIABLE @include(if: $fields_full)
    }
}
"""

QUERY_GET_VARIABLES_BY_IDS = """
query getVariables(
  $variableIds: [ID!]!
  $fields_summary: Boolean! = true
  $fields_full: Boolean! = true
  ) {
    variables(
      where: {
        id_IN: $variableIds
      }
    ) {
      ...FRAGMENT_VARIABLE_SKELETON
      ...FRAGMENT_VARIABLE_SUMMARY @include(if: $fields_summary)
      ...FRAGMENT_VARIABLE @include(if: $fields_full)
    }
  }
"""

QUERY_GET_VARIABLES = """
query getVariables(
  $fgId: ID!
  $fields_summary: Boolean! = true
  $fields_full: Boolean! = true
) {
    factorgraphs(where: { id: $fgId }) {
      variables {
        ...FRAGMENT_VARIABLE_SKELETON
        ...FRAGMENT_VARIABLE_SUMMARY @include(if: $fields_summary)
        ...FRAGMENT_VARIABLE @include(if: $fields_full)
      }
  }
}
"""

MUTATION_ADD_VARIABLES = """
mutation addVariables($variablesToCreate: [VariableCreateInput!]!) {
  addVariables(input: $variablesToCreate) {
    variables {
      ...variable_skeleton_fields
      ...variable_summary_fields
      ...variable_full_fields
    }
  }
}
"""

QUERY_LIST_VARIABLES = """
query list_variables($fgId: ID!, $varwhere: ListWhere = {}) {
  listVariables(fgId: $fgId, where: $varwhere)
}
"""


QUERY_EXISTS_VARIABLE_FACTOR_LABEL = """
query($id: ID!) {
  variables(where: { id: $id }) {
    label
  }
  factors(where: { id: $id }) {
    label
  }
}
"""

QUERY_DELETE_VARIABLE = """
mutation deleteVariable($variableId: ID!) {
  deleteVariables(
    where: { id: $variableId }
    delete: {
      ppes: {
        where: { node: { variableConnection: { node: { id: $variableId } } } }
      }
      solverData: {
        where: { node: { variableConnection: { node: { id: $variableId } } } }
      }
      blobEntries: {
        where: { node: { parentConnection: {Variable: {node: {id: $variableId } } } } }
      }
      factors: {
        where: { node: { variablesConnection_SOME: {node: {id: $variableId } } } } 
      }
    }
  ) {
    nodesDeleted
    relationshipsDeleted
  }
}
"""

QUERY_LIST_NEIGHBORS = """
query listNeighbors(
  $id: ID!
) {
  variables( where: {id: $id}) {
    factors {
      label
    }
  }
  factors( where: {id: $id}) {
    variables {
      label
    }
  }
}
"""

QUERY_FIND_VARIABLES_NEAR_TIMESTAMP = """
query findVariablesNearTime(
  $fgId: ID!
  $fromTime: DateTime!
  $toTime: DateTime!
) {
  factorgraphs(where: { id: $fgId }) {
    variables(
      where: {
        AND: [{ timestamp_GT: $fromTime }, { timestamp_LT: $toTime }]
      }
    ) {
      label
    }
  }
}
"""
